### ISSUE TITLE
Crashing loop on Firefox 123.0.1

### ISSUE THREAD

**Issue by Tech-How** [krlvm/MediaFlyout#10]
Hi, I just updated the Firefox browser to version 123.0.1, and now whenever the browser is playing media, the app will continue to flash and crash in an endless loop. If there are any logs or additional information I can provide I would be more than happy to do so, as I love this app and really hope a solution to this can be found. I'm running Windows 10.

Edit: Here are the release notes- https://www.mozilla.org/en-US/firefox/123.0.1/releasenotes/

Link to 123.0 (Working): https://ftp.mozilla.org/pub/firefox/releases/123.0/
Link to latest build, which is broken, is just on their website.

Edit 2: Could it possibly be related to this do you think? https://bugzilla.mozilla.org/show_bug.cgi?id=1881457

**Comment by krlvm** [comment]
I can't reproduce this problem, I also use Firefox 123 and Firefox Nightly > 123

Do you have any other apps with SMTC support running?

**Comment by Tech-How** [comment]
I just forced quit the browser and the app a couple times, and it went away. I haven't got it to happen again.
