### ISSUE TITLE
Impossible to get light color button

### ISSUE THREAD

**Issue by sky1ab** [krlvm/MediaFlyout#2]
you've created a nice program thank you

Windows 10 LTSC 2019 / 1809 here,

i can change windows colors, tranparency, themes, enabled/disable accents etc ....
but only black button is displayed. 
how get get the light button color like in the screenshots ?

**Comment by krlvm** [comment]
Hello, I did not test it on Windows 10 versions older than 19H1, [version 1.0.8](https://github.com/krlvm/MediaFlyout/releases/tag/v1.0.8) should fix the issue.
