### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by bropines** [krlvm/MediaFlyout#4]
Я установил, даже ручками все перенес на крайняк. Не запускается. МОжет какой-то либы нету или что?
I installed, even moved everything to the extreme with the handles. Does not start. Maybe there is no lib or what?
PS. Регион рашка

**Comment by krlvm** [comment]
Какая у вас версия Windows?
Посмотрите наличие ошибок здесь:
![image](https://user-images.githubusercontent.com/51774833/169657841-3cd8f7e8-93b3-4522-8039-48cf1cff89fe.png)

[Список поддерживаемых приложений](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md)

**Comment by bropines** [comment]
Пусто. Нет ни ошибок, ни косяков. 
Данные об OS:
Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎13.‎05.‎2022
Сборка ОС	22621.1
Взаимодействие	Windows Feature Experience Pack 1000.22632.1000.0

Имя устройства	BR0PINES-NB-PC
Процессор	AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
Оперативная память	16,0 ГБ (доступно: 15,4 ГБ)
Тип системы	64-разрядная операционная система, процессор x64
Перо и сенсорный ввод	Для этого монитора недоступен ввод с помощью пера и сенсорный ввод

Видео с док-ом: https://disk.yandex.ru/i/ZK9r-Un2UYMAag

**Comment by krlvm** [comment]
В диспетчере задач висит процесс? Несколько дней назад устанавливал сборку 22621, с ней все работало. В каком приложении вы воспроизводите звук?

**Comment by bropines** [comment]
> В диспетчере задач висит процесс?
Да.

> В каком приложении вы воспроизводите звук?
В яндекс браузере. Он его не видит. Дефолтный плеер он увидел..... Мда. Сорян за беспокойство получается.

**Comment by bropines** [comment]
Так. Ну закрою бесполезный issue. Прога просто парсит встроенную всплывашку в маленькую кнопочку. В принципе довольно прикольно. Сорян за беспокойство

**Comment by krlvm** [comment]
> Почему бы не сделать его просто по дефолту висящим в трее?

Так если ничего не воспроизводится, то и иконка не нужна.

> Так. Ну закрою бесполезный issue. Прога просто парсит встроенную всплывашку в маленькую кнопочку. В принципе довольно прикольно. Сорян за беспокойство

Я ее писал для Windows 10, где такой всплывашки в центре уведомлений нет.
Единственное, зачем она нужна лично мне на Windows 11 - если вы два раза кликните на нее, или нажмете средней кнопкой мыши, то она возобновит или приостановит воспроизведение без необходимости искать вкладку в видео в браузере или значок плеера на панели задач. Аналогично, звук отключается при клике средней кнопкой мыши на иконку EarTrumpet.
