### ISSUE TITLE
MediaFlyout missing after reboot

### ISSUE THREAD

**Issue by RickStanley** [krlvm/MediaFlyout#6]
Hi, every time I reboot, the Flyout is missing from the tray and I have to execute "install.cmd" again to make it appear again. Is this a bug or expected behaviour? I did not see any mention of this in the docs.

**Comment by krlvm** [comment]
The tray icon is hidden until some media is being played.
Is MediaFlyout still present in your Task Manager Autorun tab after reboot?

**Comment by RickStanley** [comment]
Next time I'll check, but when I login and play any media from Firefox it doesn't show up, works only after executing `ìnstall.cmd` again as I've said.

**Comment by krlvm** [comment]
Are you using Windows 11?

**Comment by RickStanley** [comment]
Window 10

**Comment by RickStanley** [comment]
@krlvm I checked that it's registered in autorun under my user name:
![grafik](https://user-images.githubusercontent.com/23178554/199531259-b5586610-24a9-4a1c-8d7d-a472ecc26e15.png)

I had it deactivated because I couldn't recognize it. Is it possible to set an icon and the "MediaFlyout" name to its entry?

**Comment by krlvm** [comment]
I think something is wrong with the installer script, which just adds the registry entry.
You can register MediaFlyout for autorun manually, for example, by placing shortcut to `shell:startup`
